site_name: yasio Documentation
docs_dir: docs
theme:
  name: material
  palette:
    scheme: slate
    primary: black
    accent: indigo
nav:
  - Home: index.md
  - API References: api/index.md
  - FAQ: faq.md
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.tasklist:
      custom_checkbox: true
