docs_dir: docs
site_name: yasio Documentation
repo_url: https://github.com/yasio/docs-437
repo_name: GitHub
edit_uri: edit/master/docs
copyright: Copyright &copy; 2012 - 2021 yasio.org.
theme:
  name: material
nav:
  - Home: index.md
  - API References:
    - io_service Class: api/reference/io_service-class.md
    - io_channel Class: api/reference/io_channel-class.md
    - io_event Class: api/reference/io_event-class.md
    - obstream Class: api/reference/obstream-class.md
    - ibstream Class: api/reference/ibstream-class.md
    - xxsocket Class: api/reference/xxsocket-class.md
    - io_service Class: api/reference/io_service-options.md
  - Preprocessor: preprocessor.md
  - FAQ: faq.md
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: yasio
      repo: docs-437
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
